import type { Metadata } from "next";
import "./globals.css";
import Header from "./(components)/header";
// import { ThemeProvider } from "./(providers)/themeprovider";
import ParticleHeader from "./(components)/particleheader";
import Footer from "./(components)/footer";
import { ReduxProvider } from "./(providers)/reduxprovider";
import SuccessModal from "./(components)/successmodal";
import Questions from "./(components)/questions";

export const metadata: Metadata = {
  title: "GalaxyFi",
  description: "Generated by create next app",
};        



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { theme } = useTheme()
  return (
    <html lang="en" suppressHydrationWarning>
      <ReduxProvider>
        <ParticleHeader />
        <body
          className={`antialiased w-full  mx-auto  min-h-screen relative z-[0] overflow-x-hidden`}
          >
            <SuccessModal />
            {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            > */}
            <Header />
            <div className="max-w-[1440px] w-full mx-auto">
              {children}
              <Questions />
            </div>
            <Footer />
            {/* </ThemeProvider> */}
        </body>  
      </ReduxProvider>
    </html>
  );
}
