import type { Metadata } from "next";
import "./globals.css";
import Header from "./(components)/header";
import { ThemeProvider } from "./(providers)/themeprovider";
import ParticleHeader from "./(components)/particleheader";
import Footer from "./(components)/footer";
// import { useTheme } from "next-themes";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};  

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { theme } = useTheme()
  return (
    <html lang="en" suppressHydrationWarning>
      <ParticleHeader />
      <body
        className={`antialiased w-full max-w-[1440px] mx-auto border min-h-screen relative z-[0] px-3`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
